# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet tool install -g Cake.Tool
  displayName: 'Install Cake'

- script: |
    dotnet restore src/DevopsHelloWorld
  displayName: 'Restore Project'

- script: dotnet restore src/DevopsHelloWorld.Tests
  displayName: 'Restore Unit Test'

- script: dotnet test src/DevopsHelloWorld.Tests
  displayName: 'Execute Unit Test'

- script: ~/.dotnet/tools/dotnet-cake 
  displayName: 'Publish Project'

- task: GitHubRelease@0
  displayName: 'Github Release (Create)'
  inputs:
    repositoryName: '$(Build.Repository.Name)'
    gitHubConnection: 'github.com'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '0.1.0.$(Build.BuildNumber)'
    title: '0.1.0.$(Build.BuildNumber)'
    releaseNotes: ':rocket: $(Build.BuildNumber)'
    assets: 'publish.zip'